name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Add SSH key for EC2 access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: SSH into EC2 and deploy
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          ssh -o StrictHostKeyChecking=no -t $EC2_USER@$EC2_HOST << 'EOF'
          
            # Ensure known hosts include GitHub to avoid verification issues
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

            # Check if the CG_Improvements directory exists
            cd ~
            if [ ! -d "CG_Improvements" ]; then
              git clone git@github.com:atulwaster24/CG_Improvements.git ~/CG_Improvements
            fi
            cd ~/CG_Improvements

            # Set up environment variables
            echo "MONGO_URI=$MONGO_URI" > .env  # Create .env file with Mongo URI

            # Install dependencies and build
            npm install
            npm run build
            ./config/scripts/deploy.sh
          EOF
