name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code locally
        uses: actions/checkout@v3

      - name: Set up Node.js locally
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: SSH into EC2 and deploy
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          MONGO_URI: ${{ secrets.MONGO_URI }}  # Pass Mongo URI
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd ~

            # Check if the CG_Improvements directory exists
            if [ ! -d "CG_Improvements" ]; then
            # If it doesn't exist, clone the repository
            git clone https://github.com/atulwaster24/CG_Improvements.git
            fi

            # Navigate to the project directory
            cd /CG_Improvements

            # Set up environment variables
            echo "MONGO_URI=$MONGO_URI" > .env  # Create .env file with Mongo URI

            # Install dependencies
            npm install

            # Build the Next.js app
            npm run build

            # Run the deployment script
            ./config/scripts/deploy.sh
          EOF
